USE ProyectoProgra4
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Año](
    [Id_Año] [int] IDENTITY(1,1) NOT NULL,
    [Año] [varchar](5) NULL,
PRIMARY KEY CLUSTERED 
(
    [Id_Año] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET IDENTITY_INSERT [dbo].[Año] ON;
GO


INSERT INTO [dbo].[Año]([Id_Año],[Año]) 
VALUES 
	(1,'2019'),
	(2,'2020'),
	(3,'2021')
GO

SELECT * FROM [dbo].[Año]